# Generated by Django 3.1.4 on 2021-01-02 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='email',
            field=models.EmailField(default=datetime.datetime(2021, 1, 2, 14, 29, 43, 66880, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='city',
            field=models.CharField(max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='state',
            field=models.CharField(max_length=200, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='zipcode',
            field=models.CharField(max_length=200, null=True, verbose_name='Zipcode'),
        ),
    ]
