# Generated by Django 3.1.4 on 2021-01-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
