# Generated by Django 3.1.4 on 2021-01-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210104_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessages',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessages',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactmessages',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessages',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
